steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']

  # Build TypeScript
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']

  # Deploy Cloud Function
  # Note: Using ^;^ delimiter to allow commas in ALLOWED_USERS value
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - ${_FUNCTION_NAME}
      - --gen2
      - --runtime=nodejs20
      - --region=${_REGION}
      - --source=.
      - --entry-point=deployBot
      - --trigger-http
      - --allow-unauthenticated
      - --service-account=${_FUNCTION_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
      - --set-secrets=SLACK_SIGNING_SECRET=slack-signing-secret:latest
      - --set-env-vars=^;^ALLOWED_USERS=${_ALLOWED_USERS};STAGING_PROJECT_ID=${_STAGING_PROJECT_ID};PROD_PROJECT_ID=${_PROD_PROJECT_ID};FUNCTION_REGION=${_REGION}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: eu-west1
  _FUNCTION_NAME: slack-deploy-bot
  _STAGING_PROJECT_ID: ''
  _PROD_PROJECT_ID: ''
  _ALLOWED_USERS: ''
